insert into vendor (code, name) values ('CAP', 'Capella Flavors');

insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), '27 Bears');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), '27 Fish');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Acai');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Amaretto');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Anise');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apple Pie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apple Pie v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apple Snacks');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apricot');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Banana');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Banana Split');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bavarian Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Biscuit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Black Currant');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blackberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blue Raspberry Cotton Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blueberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blueberry Cinnamon Crumble');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blueberry Extra');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blueberry Jam');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blueberry Pomegranate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bold Tobacco');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Boston Cream Pie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Boston Cream Pie v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bubble Gum');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Butter Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Butter Pecan');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Butterscotch');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cake Batter');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Candied Watermelon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cantaloupe');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cappuccino');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cappuccino v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Caramel');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Caramel v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cereal 27');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Chai Tea');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cherry Cola');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Chocolate Caramel Nut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Chocolate Coconut Almond');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Chocolate Fudge Brownie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Chocolate Fudge Brownie v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Chocolate Glazed Doughnut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Churro');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cinnamon Coffee Cake');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cinnamon Danish Swirl');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cinnamon Danish Swirl v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cinnamon Sugar');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Coconut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cola');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Concord Grape');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cool Mint');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cotton Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cranberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Creamy Yogurt');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cucumber');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cup of Joe');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Double Apple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Double Chocolate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Double Chocolate v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Double Watermelon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Dragon Fruit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Dutch Chocolate Mint');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Egg Nog');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Energy Drink');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Espresso');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Fig');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'French Toast');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'French Vanilla');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'French Vanilla v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Fruit Circles');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Fuji Apple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Funnel Cake');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Gingerbread');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Glazed Doughnut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Golden Butter');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Golden Pineapple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Graham Cracker');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Graham Cracker v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Grape');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Grape Concord');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Grapefruit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Greek Yogurt');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Green Apple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Green Apple Hard Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Grenadine');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Harvest Berry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Hazelnut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Hazelnut v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Hibiscus');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Honey');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Honeydew Melon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Horchata');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Hot Cinnamon Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Hot Cocoa');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Irish Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Italian Lemon Sicily');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Jelly Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Juicy Lemon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Juicy Orange');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Juicy Peach');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Kiwi');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Kiwi Strawberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lemon Lime');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lemon Meringue Pie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lemon Meringue Pie v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lime');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Maple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Marshmallow');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Menthol');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Meringue');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Milk Chocolate Toffee');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'New York Cheesecake');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'New York Cheesecake v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Orange Creamsicle');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Orange Mango');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Passion Fruit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peach with Stevia');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peaches and Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peaches and Cream v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peanut Butter');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peanut Butter v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pear');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peppermint');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pina Colada');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pina Colada v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pink Lemonade');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pomegranate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pomegranate v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Popcorn');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Popcorn v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Powerful Sour');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pralines and Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pumpkin Pie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Rainbow Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Raspberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Raspberry v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Root Beer');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Simply Vanilla');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Smooth Tobacco');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Spearmint');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Strawberries and Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Strawberry Taffy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sugar Cookie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sugar Cookie v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Super Sweet');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet Guava');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet Lychee');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet Mango');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet Strawberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet Tangerine');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet Tea');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet Watermelon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Toasted Almond');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Bean Ice Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Cupcake');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Cupcake V2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Custard');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Custard v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Whipped Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Waffle');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Whipped Marshmallow');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Wild Cherry with Stevia');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Yellow Cake');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Yellow Peach');

insert into vendor (code, name) values ('FA', 'FlavourArt');

insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), '7 Leaves Ultimate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'AAA Magic Mask');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Ace Asso');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Almond');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Anise');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apple Pie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apricot');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Aurora');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Banana');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bavarian Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bergamot');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bilberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bitter Wizard');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Black Fire');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Black Pepper');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Black Tea');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Black Touch');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blackberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blackcurrant');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blenderize');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blood Orange');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Brandy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Breakfast Cereal');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Burley');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Butter');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Butterscotch');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cam Blend Ultimate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'CandyJammy Wizard');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cantaloupe');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cappuccino');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Caramel');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cardamom');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Catalan Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cherry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cherry Black');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Chocolate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Chocolate Glazed Doughnut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cigar Passion');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cinnamon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Citrus Mix');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Clove');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cocoa');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Coconut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cocoon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Coffee Espresso');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cola');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cookie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Corn');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cornish Cream Tea');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cowboy Blend');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cream Fresh');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Croissant');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cuban Supreme');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cucumber');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Custard');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Custard Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Custard Premium');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Dark Vapure');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Desert Ship');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Dragonfruit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Dusk');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Fig Fresh');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Flash');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Florida Key Lime');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Forest Fruit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Fuji Apple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Gin');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Glory');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Graham Crust');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Grape Concord');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Grape White');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Grapefruit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Green Tea');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Guava');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Hazelnut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Honey');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Hypnotic Myst');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Irish Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Jack Fante');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Jasmine');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Joker Burlone');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Joy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Juicy Strawberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'King RE');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Kiwi');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Labyrinth');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Latakia');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lavender');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lemon Sicily');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lemon Zest');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lime Tahity');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Liquid Amber');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lychee');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Madagascar');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'MadMix');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mandarin');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mango');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mangosteen');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Maple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Marshmallow');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Marzipan');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Maxx Blend');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mellow Sunset');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Menthol');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Meringue');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Metaphor');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Milk');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Milk Condensed');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Monsoon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Morning Sun');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'MTS Vape Wizard');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'New York Cheesecake');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Nonnas Cake');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Nut Mix');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Oak Wood');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Oba Oba');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Orange');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pandoro');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Papaya');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Passion');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peach');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peach White');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peanut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pear');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peppermint');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Perique Black');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pineapple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pistachio');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Polar Blast');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pomegranate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Queen Regina');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Raspberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Rose');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Royal');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Royal Orange Juice');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Rum Jamaican Special');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'RY4');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Saffron');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Shade');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Soho');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sour Wizard');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Spearmint');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Storm');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Strawberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Summer Clouds');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tiramisu');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Torrone');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tuscan Reserve');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Bourbon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Ice Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Tahity');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vienna Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Violet');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Virginia');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Walnut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Watermelon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Whipped Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Whisky');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Wine Champagne');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Ylang Ylang');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Yogurt');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Yougurt');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Zen Garden');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Zeppola');

insert into vendor (code, name) values ('FLV', 'Flavorah');

insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Alpine Strawberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apple Cider');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apple Filling');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apple Pop');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apricot');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Banana');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Basil');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Beer Nuts');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Berry Blend');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bing Cherry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Biscotti');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Black Cherry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Black Tea');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blood Orange');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blueberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blueberry Muffin');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bourbon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Boysenberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Brie Cheese');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bubble Gum');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Butterscotch');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Candy Roll');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cantaloupe');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Caramel');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cavendish');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cheesecake');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cherimoya');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Chocolate Deutsch');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cinnamon Crunch');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Coconut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Coffee');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Connecticut Shade');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cookie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cookie Dough');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cool Menthol');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cotton Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cranberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cream and Cookies');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Creme de Menthe');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Crunch Cereal');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cupcake Batter');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cured Tobacco');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Custard');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Dragon Fruit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Eggnog');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Elderflower');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Fig');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Fried Dough');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Frosting');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Ginger');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Ginger Snap');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Graham Cracker');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Granola');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Grape');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Greek Yogurt');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Green Apple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Guanabana');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Honey Bee');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Ice');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Irish Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Jackfruit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Kentucky Blend');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lemon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lemon Grass');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lemon Tea');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lemonade');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lime');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lime Wedge');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lychee');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Macaroon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mango');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Maple Bar');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Marshmallow');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Milk');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Milk and Honey');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Milk Chocolate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mocha');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Native tobacco');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Oak Barrel');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Oatmeal Raisin');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Orange Citrus');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Oriental Tobacco');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Papaya Punch');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Passion Fruit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pastry Zest');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peach');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peach Gummy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peanut Butter');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pear');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Persimmon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pineapple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pink Guava');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pistachio');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Popcorn');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pound Cake');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pumpkin Spice');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Raisin Rum');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Raspberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Red Apple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Red Burley');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Red Raspberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Rich Cinnamon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Root Beer');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Smoked Butterscotch');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Smooth Vanilla');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sour Apple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Soursop');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Spearmint');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Strawberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Strawberry Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Strawberry Filling');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Strawberry Smash');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet Coconut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet Dough');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweetness');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tangerine');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tatanka Tobacco');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Thai Chai');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Toffee');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tricks Cereal');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tropical Citrus');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tropical Punch');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Turkish Tobacco');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Bean');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Custard');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Pudding');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Virginia Tobacco');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Watermelon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Whipped Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'White Chocolate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Wild Melon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Yakima Hops');

insert into vendor (code, name) values ('INW', 'Inawera');

insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), '555 Gold');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), '7 Leaves');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Almond');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Am4A');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Anise');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Anton Apple YC');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apricot');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bahraini Apple Gold');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Banana');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Biscuit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Black Cherry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Black Cherry for Pipe');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Black For Pipe Classic');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Black Fruit Mint');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Black Jack Tobacco');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blackberry and Raspberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blackcurrant');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blueberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Brandy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bubble Gum Donald');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bubble Gum Yummy Classic');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Burley');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cactus');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cactus Lime');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cake Lemon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cappuccino');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Caramel');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Caribbean Blend');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cherimoya YC');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cherries');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cherry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Chocolate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Chocolate Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Coconut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Coconut Cookies');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cocopilada');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Coffee');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cola');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Creme Brulee');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Custard');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cytryna');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Dark For Pipe Classic');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Desert Ship');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Dragon Fruit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Dromedary');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Ethyl Maltol 10');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Eucalyptus and Mint');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Exotic');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Flue Cured Tobacco TdM');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'French Pipe');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Gold Ducat');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Grape');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Grapefruit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Grapes');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Honey');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Jamaican Rum');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Juicy Lemon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'kiwi');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lemon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lemon Mix WG');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Licorice');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lime');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mango');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Marzipan');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Melon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Menthol');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Milk Chocolate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mint');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Miss Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mississippi');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mixed Mint');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mocha');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Natural Mint');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Nugat');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Nutty Princess');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Orange');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peach');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peanuts');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pear');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pina Colada');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pineapple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pink Panther');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Plum');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Purple Gum');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Raspberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Red Fruits And Mint');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Rhubarb YC');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sesame Sweets');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Shisha Apple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Shisha Banana');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Shisha Bilberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Shisha Cherry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Shisha Coconut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Shisha Golden Apple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Shisha Lemon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Shisha Lime');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Shisha Mango');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Shisha Orange');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Shisha Pineapple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Shisha Raspberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Shisha Strawberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Shisha Vanilla');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Smoked Plum');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sparkling Wine');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Spicy Biscuit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Strawberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Strawberry kiss');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Strawberry Wild');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet Sour');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tiramisu');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'tobacco absolute cigar');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tobacco Absolute Garuda');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tobacco Absolute Virginia');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tobacco Cavendish WG');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tobacco DNB');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tobacco Symphony');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Two Apples');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Bourbon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Classic');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla for Pipe');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Virginia');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Waffle');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Watermelon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'White Grapefruit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Yes We Cheesecake');

insert into vendor (code, name) values ('TFA', 'The Flavor Apprentice');

insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), '20 Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Absinthe');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Absinthe II');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Acai Berry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Acetyl Pyrazine 5');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Almond');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Almond Amaretto');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'American Red Tobacco');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Anise');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apple Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apple Pie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Apricot');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Banana');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Banana Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Banana Nut Bread');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bananas Foster');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bavarian Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Berry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Berry Mix');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bittersweet Chocolate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Black Cherry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Black Currant');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Black Honey');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Black Tea');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blackberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blood Orange');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blue Raspberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blueberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blueberry Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blueberry Extra');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Blueberry Wild');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bourbon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Boysenberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Boysenberry Deluxe');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Brandy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Brown Sugar');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Bubblegum');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Butter');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Butterscotch');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cantaloupe');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cappuccino');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Caramel');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Caramel Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Caramel Cappuccino');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Caramel Original');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'caramel v2');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Chai Tea');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Champagne');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cheesecake');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cherry Blossom');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cherry Extract');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Chocolate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Chocolate Coconut Almond Candy Bar');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cigarillo');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cinnamon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cinnamon Danish');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cinnamon Red Hot');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cinnamon Spice');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cinnamon Sugar Cookie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Citrus Punch');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Citrus Punch II');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Clove');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cocoa Rounds');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Coconut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Coconut Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Coconut Extra');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Coffee');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Coffee Extra');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cola');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cola Cherry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cola Syrup');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Condensed Milk');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cotton Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cranberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cranberry Sauce');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cream Soda');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Creme de Menthe');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Creme De Menthe II');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Crunchy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cubano Type');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Cucumber');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Dairy Milk');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Dark Rum');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'DK Tobacco Base');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Double Chocolate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Dr Pop');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Dragonfruit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Dulce de Leche');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Dulce de Leche Caramel');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'DX French Vanilla');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'DX Vanilla Custard');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'DX Whipped Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Earl Grey Tea');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Eggnog');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Elderberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Energy Drink');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'English Toffee');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Espresso');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Ethyl Malthol 5');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Ethyl Vanillin 10');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Eucalyptus');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'French Vanilla');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'French Vanilla Creme');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'French Vanilla Deluxe');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'French Vanilla II');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Frosted Donut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Fruit Circles');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Fruit Circles with Milk');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Fruity Stick Gum');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Fudge Brownie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Ginger Ale');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Gingerbread');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Gingerbread Cookie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Graham Cracker');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Grape Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Grape Juice');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Grape Soda');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Greek Yogurt');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Green Apple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Green Tea');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Guava');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Gummy Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Hawaiian Drink');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Hazelnut');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Hazelnut Praline');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Hibiscus');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Holiday Spice');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Honey');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Honey Circles Cereal');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Honeydew');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Honeydew II');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Honeysuckle');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Horchata');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Horchata Smooth');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Horehound');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Hpno Type');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Huckleberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Hypno');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Irish Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Jackfruit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Jamaican Rum');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Juicy Peach');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'kalua and cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Kentucky Bourbon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Kettle Corn');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Key Lime');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Key Lime Pie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Kiwi');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Koolada 10');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lemon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lemon II');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lemon Lime');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lemon Lime II');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lemonade Cookie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lucky Leprechaun Cereal');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Lychee');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Madagascar Bourbon Vanilla');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Malted Milk');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mango');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Maple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Maple Syrup');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Maraschino Cherry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Marshmallow');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mary Jane');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Menthol');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Menthol 10');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Meringue');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mexican Coffee');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mexican Liqueur');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Milk Chocolate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'MilkDairy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mint Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mocha');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mojito');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Mojito Havana');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Molasses');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'M-Type Premium');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Musk Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Nectarine');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Oatmeal Cookie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Orange Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Orange Mandarin');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pancake');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Papaya');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Passion Fruit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peach');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peanut Butter');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pear');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pear Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pecan');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peppermint');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Peppermint II');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Philippine Mango');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pie Crust');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pina Colada');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pineapple');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pineapple Juicy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pistachio');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Plum');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pomegranate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pomegranate Deluxe');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Popcorn');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Popcorn Movie Theater');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pralines and Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pumpkin');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Pumpkin Spice');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Quince');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Rainbow Drops');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Rainbow Sherbet');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Raisin');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Raspberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Raspberry Sweet');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Red Licorice');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Red Oak');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Red Type Blend');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Red Type II Blend');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Red Velvet');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Red Velvet Cake');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Rice Crunchies');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Ripe Banana');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Root Beer');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Root Beer Float');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Rose Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'RY4');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'RY4 Asian');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'RY4 Double');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Silly Rabbit');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Slim Mint Cookie');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Smooth');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sour');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Spearmint');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Strawberries and Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Strawberry');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Strawberry lemonade');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Strawberry Organic');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Strawberry Ripe');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Swedish Gummy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet and Tart');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet Cereal Flakes');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet Cream DX');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweet Tea');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Sweetener');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Taro');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tiramisu');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Toasted Almond');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Toasted Marshmallow');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tobacco');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tobacco Blend');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Turkish');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Tutti Frutti Deluxe');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Bean Gelato');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Bean Ice Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Cupcake');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Custard');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanilla Swirl');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Vanillin 10');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Violet Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Waffle');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Watermelon');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Watermelon Candy');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Western');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Whipped Cream');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'White Chocolate');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Wintergreen');
insert into flavor (vendor_id, name) values (currval('vendor_id_seq'), 'Yam');